"""add_player_event_log_and_patent_lore

Revision ID: 5260b79e3f57
Revises: da2c8c3484aa
Create Date: 2026-06-17 21:14:09.689404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5260b79e3f57'
down_revision: Union[str, Sequence[str], None] = 'da2c8c3484aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_events_log',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['core.players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='core'
    )
    op.create_index('idx_player_events_player_id', 'player_events_log', ['player_id'], unique=False, schema='core')
    op.add_column('patents', sa.Column('lore_name', sa.String(length=100), nullable=True), schema='crafting')
    op.add_column('patents', sa.Column('lore_text', sa.String(length=500), nullable=True), schema='crafting')
    op.add_column('patents', sa.Column('card_image_file_id', sa.String(length=200), nullable=True), schema='crafting')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patents', 'card_image_file_id', schema='crafting')
    op.drop_column('patents', 'lore_text', schema='crafting')
    op.drop_column('patents', 'lore_name', schema='crafting')
    op.drop_index('idx_player_events_player_id', table_name='player_events_log', schema='core')
    op.drop_table('player_events_log', schema='core')
    # ### end Alembic commands ###
