"""add_hud_message_id

Revision ID: 68c49c3c8213
Revises: 5260b79e3f57
Create Date: 2026-06-17 21:14:31.609254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c49c3c8213'
down_revision: Union[str, Sequence[str], None] = '5260b79e3f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('hud_message_id', sa.BigInteger(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'hud_message_id', schema='core')
    # ### end Alembic commands ###
