"""add_ingredient_prices

Revision ID: 8632fe8dfa46
Revises: 68c49c3c8213
Create Date: 2026-06-17 21:16:15.383475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8632fe8dfa46'
down_revision: Union[str, Sequence[str], None] = '68c49c3c8213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_prices',
    sa.Column('ingredient', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trend', sa.SmallInteger(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ingredient'),
    schema='economy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_prices', schema='economy')
    # ### end Alembic commands ###
