"""Initial migration

Revision ID: ad576d47ae22
Revises: 
Create Date: 2026-06-15 18:03:04.842893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad576d47ae22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('prestige_crystals', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.SmallInteger(), nullable=False),
    sa.Column('influence', sa.SmallInteger(), nullable=False),
    sa.Column('suspicion', sa.SmallInteger(), nullable=False, server_default=sa.text('0')),
    sa.Column('tavern_level', postgresql.ENUM('garage', 'tavern', 'brewery', 'factory', 'guild', name='tavern_tier', schema='core'), nullable=False),
    sa.Column('last_offline_calc_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gold >= 0', name='chk_player_gold'),
    sa.CheckConstraint('influence BETWEEN 0 AND 100', name='chk_player_influence'),
    sa.CheckConstraint('prestige_crystals >= 0', name='chk_player_crystals'),
    sa.CheckConstraint('reputation BETWEEN -100 AND 100', name='chk_player_reputation'),
    sa.CheckConstraint('suspicion BETWEEN 0 AND 100', name='chk_player_suspicion'),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('tg_id'),
    schema='core'
    )
    op.create_index('idx_players_tg_id', 'players', ['tg_id'], unique=False, schema='core')
    op.create_table('market_saturation',
    sa.Column('market_segment', sa.String(length=20), nullable=False),
    sa.Column('volume_sold_24h', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('market_segment'),
    schema='economy'
    )
    op.create_table('transactions_log',
    sa.Column('tx_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('processed_for_royalty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tx_id'),
    schema='economy'
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    schema='queue'
    )
    op.create_table('resources',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_resource_qty'),
    sa.ForeignKeyConstraint(['player_id'], ['core.players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'resource_type'),
    schema='core'
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', postgresql.ENUM('master_alchemist', 'caravaner', 'merchant', name='staff_role', schema='core'), nullable=False),
    sa.Column('skill', sa.SmallInteger(), nullable=False),
    sa.Column('loyalty', sa.SmallInteger(), nullable=False),
    sa.Column('fatigue', sa.SmallInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('healthy', 'light_injured', 'heavy_injured', 'dead', name='staff_status', schema='core'), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fatigue BETWEEN 0 AND 100', name='chk_staff_fatigue'),
    sa.CheckConstraint('loyalty BETWEEN 0 AND 100', name='chk_staff_loyalty'),
    sa.CheckConstraint('skill BETWEEN 1 AND 100', name='chk_staff_skill'),
    sa.ForeignKeyConstraint(['player_id'], ['core.players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id'),
    schema='core'
    )
    op.create_index('idx_staff_player_id', 'staff', ['player_id'], unique=False, schema='core')
    op.create_table('recipes',
    sa.Column('recipe_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('malt_pct', sa.SmallInteger(), nullable=False),
    sa.Column('water_pct', sa.SmallInteger(), nullable=False),
    sa.Column('hop_pct', sa.SmallInteger(), nullable=False),
    sa.Column('yeast_pct', sa.SmallInteger(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('bitterness', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('aroma', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('stability', sa.SmallInteger(), nullable=False),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('aroma BETWEEN 0.00 AND 20.00', name='chk_beer_aroma'),
    sa.CheckConstraint('bitterness BETWEEN 0.00 AND 20.00', name='chk_beer_bitterness'),
    sa.CheckConstraint('hop_pct BETWEEN 0 AND 100', name='chk_hop_range'),
    sa.CheckConstraint('malt_pct + water_pct + hop_pct + yeast_pct = 100', name='chk_total_proportions_100'),
    sa.CheckConstraint('malt_pct BETWEEN 0 AND 100', name='chk_malt_range'),
    sa.CheckConstraint('stability BETWEEN 0 AND 100', name='chk_beer_stability'),
    sa.CheckConstraint('strength BETWEEN 0.00 AND 20.00', name='chk_beer_strength'),
    sa.CheckConstraint('water_pct BETWEEN 0 AND 100', name='chk_water_range'),
    sa.CheckConstraint('yeast_pct BETWEEN 0 AND 100', name='chk_yeast_range'),
    sa.ForeignKeyConstraint(['creator_id'], ['core.players.player_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('recipe_id'),
    schema='crafting'
    )
    op.create_index('idx_recipes_stats_search', 'recipes', ['strength', 'bitterness', 'aroma'], unique=False, schema='crafting')
    op.create_table('batches',
    sa.Column('batch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_barrels', sa.Integer(), nullable=False),
    sa.Column('quality_modifier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_spoiled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_barrels >= 0', name='chk_batch_quantity'),
    sa.ForeignKeyConstraint(['player_id'], ['core.players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['crafting.recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('batch_id'),
    schema='crafting'
    )
    op.create_index('idx_batches_player_inventory', 'batches', ['player_id'], unique=False, schema='crafting', postgresql_where=sa.text('quantity_barrels > 0'))
    op.create_index('idx_batches_uncompleted', 'batches', ['ready_at'], unique=False, schema='crafting', postgresql_where=sa.text('is_completed = FALSE'))
    op.create_table('patents',
    sa.Column('patent_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_tax_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('royalty_earned_24h', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['core.players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['crafting.recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('patent_id'),
    schema='crafting'
    )
    op.create_index('idx_patents_active', 'patents', ['player_id'], unique=False, schema='crafting', postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_patents_active', table_name='patents', schema='crafting', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('patents', schema='crafting')
    op.drop_index('idx_batches_uncompleted', table_name='batches', schema='crafting', postgresql_where=sa.text('is_completed = FALSE'))
    op.drop_index('idx_batches_player_inventory', table_name='batches', schema='crafting', postgresql_where=sa.text('quantity_barrels > 0'))
    op.drop_table('batches', schema='crafting')
    op.drop_index('idx_recipes_stats_search', table_name='recipes', schema='crafting')
    op.drop_table('recipes', schema='crafting')
    op.drop_index('idx_staff_player_id', table_name='staff', schema='core')
    op.drop_table('staff', schema='core')
    op.drop_table('resources', schema='core')
    op.drop_table('tasks', schema='queue')
    op.drop_table('transactions_log', schema='economy')
    op.drop_table('market_saturation', schema='economy')
    op.drop_index('idx_players_tg_id', table_name='players', schema='core')
    op.drop_table('players', schema='core')
    # ### end Alembic commands ###
