"""add tutorial_step to player

Revision ID: da2c8c3484aa
Revises: ad576d47ae22
Create Date: 2026-06-15 20:42:30.144265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2c8c3484aa'
down_revision: Union[str, Sequence[str], None] = 'ad576d47ae22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('tutorial_step', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'tutorial_step', schema='core')
    # ### end Alembic commands ###
